services:
  server:
    build:
      context: ./server
    container_name: wordle_server
    ports:
      - "3002:3000"
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/db:/usr/src/app/db
      - ./server/nest-cli.json:/usr/src/app/nest-cli.json
    command: npm run start:dev

  client:
    image: node:20-alpine
    container_name: wordle_client
    working_dir: /app
    ports:
      - "8082:8080"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - server
